In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [15]:
food = np.array(["Pakora", "Samosa","Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [16]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [17]:
type(price)

numpy.ndarray

In [18]:
type(food)

numpy.ndarray

In [19]:
len(price)

3

In [20]:
len(food)

3

In [23]:
price[:]

array([5, 5, 5])

In [24]:
price.mean()

5.0

In [25]:
#zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
#empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [33]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [37]:
np.linspace(1,100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [39]:
# specify your data type

np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [40]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array Functions

In [2]:
import numpy as np

In [4]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [6]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [7]:
b = np.array([10.2,3.4,53.6,45.6,91.6])
b

array([10.2,  3.4, 53.6, 45.6, 91.6])

In [10]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  45.6,  91.6])

In [12]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.6,  53.6,  91.6, 100. , 320. ])

# 2-D arrays

In [13]:
a = np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [14]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [20]:
c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 3, 4, 5, 6, 7],
       [5, 4, 3, 2, 1, 8, 9]])

In [22]:
d = np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [24]:
f = np.concatenate((b,d), axis=1)
f

array([[6, 7, 1, 2],
       [8, 9, 3, 4]])

In [25]:
# to find the number of dimesions
f.ndim

2

In [27]:
b = np.array([[5,6,7],[8,9,10],[10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [28]:
b.ndim

2

In [29]:
#to find the no of elements
b.size

9

In [31]:
#shape
b.shape

(3, 3)

In [38]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
#reshape
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
#reshape

np.reshape(a, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [41]:
# convert 1D into 2D

a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a.shape

(9,)

In [45]:
# row wise conversion

b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [46]:
b.shape

(1, 9)

In [47]:
# col wise conversion

c = a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [48]:
c.shape

(9, 1)